POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker 2"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/c817f35a-1df4-4218-a483-2ef7bd0cb5ce
###

PUT  http://localhost:3333/courses/deac93db-005b-4bb5-9d15-a3cd2d9cef05
Content-Type: application/json

{
    "title": "TESTE"
}

###

DELETE  http://localhost:3333/courses/deac93db-005b-4bb5-9d15-a3cd2d9cef05